### ISSUE TITLE
Log prints stack traces to standard error instead of logging them

### ISSUE THREAD

**Issue by bokesan** [rapidoid/rapidoid#167]
The Log methods taking a Throwable always write the stack trace to standard error.
I was always wondering whether my config was wrong until I looked into the source: it actually uses `Throwable.printStackTrace`. Is this by design? I really need stack traces in the regular log output.

**Comment by nmihajlovski** [comment]
This was by design, to provide a way to log the error and print stack trace on std-err when calling e.g. `Log.error(msg, err);`.

The functionality that you need can be achieved by providing the exception as argument e.g. `Log.error(msg, "error", err);`.

However, I am refactoring the logging mechanism now, to unify both ways of logging, which will reduce the surprises like that. The target output for stack traces will be configurable.

**Comment by bokesan** [comment]
Thanks, works for me! (And you are right about surprises - I'd never have guessed that the stack trace would be printed when the Throwable is given as an argument).
