### ISSUE TITLE
Support http-fast all in one jar.

### ISSUE THREAD

**Issue by lefay1982** [rapidoid/rapidoid#44]
I want reference one jar of http-fast (like netty-all ),   and only use http-fast,  do not use web module.
can you add this feature?

**Comment by nmihajlovski** [comment]
I am not sure I understand this issue.

You can already reference just the "http-fast" module, without the "web" module, as described here:
http://www.rapidoid.org/http-fast.html

Is this issue is about having all-in-one JAR containing http-fast and its dependencies? Which build tool would you use in such case?

**Comment by lefay1982** [comment]
if I not use maven , I must copy many jars into my project's libs folder.
but if all in one jar, I only copy one jar into it.

**Comment by lefay1982** [comment]
Yes, one JAR containing http-fast and its dependencies.
maybe name is     rapidoid-http-fast-all.jar

**Comment by nmihajlovski** [comment]
You make a valid point. It's nice to have all-in-one JARs of both the "Http Fast" and "Web" modules, indeed. Coming soon...

**Comment by lefay1982** [comment]
Yes, if   TCP module can use  standalone, also can  have all-in-one JAR.
Good job.

**Comment by nmihajlovski** [comment]
As the number of modules that could have all-in-one JAR increases, it would be an over-kill to publish such uber-jars for all of them. On the other hand, it would be strange to provide uber-jars just for part of them. Since most users use Maven or Docker, I am canceling this.
