### ISSUE TITLE
Cannot run after using Gradle to build jar file.

### ISSUE THREAD

**Issue by doggie1989** [rapidoid/rapidoid#66]

**Comment by nmihajlovski** [comment]
Can you please provide more context/information?

**Comment by doggie1989** [comment]
@nmihajlovski 
I can run in eclipse via main(),but after I build a jar, I could not run it.

**Comment by wmacgyver** [comment]
@doggie1989 are you using gradle's shadow plugin to build a uberjar? because I just tried it and it's working for me

**Comment by doggie1989** [comment]
@wmacgyver 
Hi Mate,Could you share the build.gradle file?
I was using gradle 'jar' plugin and build cmd.

**Comment by wmacgyver** [comment]
@doggie1989 ah yea, that won't work. because rapidoid comes with embedded server, so you have to run it as a uber jar.

here is my build.gradle

plugins {
    id 'com.github.johnrengelman.shadow' version '1.2.3'
}

apply plugin: 'java'
apply plugin: 'application'

mainClassName = 'my.app.Main'

repositories {
    mavenCentral()
}

dependencies {
    def rapidoidVersion = '5.1.4'
    def slf4jVersion = '1.7.21'

    compile "org.rapidoid:rapidoid-http-server:${rapidoidVersion}"
    compileOnly "org.rapidoid:rapidoid-watch:${rapidoidVersion}"
    runtime "org.slf4j:slf4j-simple:${slf4jVersion}"
}


you build the uber jar by doing gradle shadow, it will produce a uber jar in build/libs. when you do jar -jar foo.jar. it will run the class my.app.main as I defined here.

**Comment by doggie1989** [comment]
@wmacgyver 

Thanks brother.
All working well now!!!

I am migrating my app from spring boot...

**Comment by wmacgyver** [comment]
@doggie1989 yea, you didn't have to do this with spring boot for gradle because the spring boot plugin extends application. so it's silently doing it in the background as magic if you will. we too have moved from spring boot.

**Comment by doggie1989** [comment]
@wmacgyver hi mate, now I have some static files in static folder, when I start Rapidoid in eclipse,it works,but it does not work after packing it and run via java -jar...it looks that the static files have not ben packed into jar...do you know how to solve it?
