### ISSUE TITLE
XML response support

### ISSUE THREAD

**Issue by ferrerojosh** [rapidoid/rapidoid#99]
This will be good for porting to rapidoid on legacy systems.

**Comment by cyterdan** [comment]
Hi, big fan of rapidoid !

I'd like to give this a go, any indications on how to proceed?

I've identified the following : 

- add xml(...) methods to OnRoute.java
- add interfaces and default implementations for XMLResponseRenderer and XMLRequestRequestBodyParser 
- ???
- update tests and doc

**Comment by nmihajlovski** [comment]
Hi, it's great to hear that, thanks!

Yes, basically that sounds like a good plan. Please take a look at `org.rapidoid.data.XML`, the default implementation should use that. And `org.rapidoid.http.customize.Customization` would have the new interfaces included.

Also, `XMLRequestRequestBodyParser` was probably a typo, you mean `XMLRequestBodyParser`, right?

Cheers and good luck!

**Comment by cyterdan** [comment]
Yep typo :)

Ok then I'll let you know how it goes

**Comment by cyterdan** [comment]
Since jackson is already used for Json, I was thinking it would be better to use jackson-dataformat-xml to serialize instead of Jaxb used in `org.rapidoid.data.XML`

**Comment by nmihajlovski** [comment]
Sure, sounds reasonable!

**Comment by cyterdan** [comment]
Currently the response content-type for errors defaults to json (or html if the module is loaded). I'm wondering how to handle this when writing an XML API.

1. make the default `contentType` a field in `org.rapidoid.http.customize.Customization` with the default being json, allowing the user to set it to xml (but then it's a bit confusing because of the html part)
2. leave the `contentType` as json for errors and let the user customize the `errorHandler` if they want xml error handling.

Any thoughts?

**Comment by nmihajlovski** [comment]
That is a very good point!

I am afraid [1] would be outside the scope of this issue, and it won't really solve the problem, since some setups could have multiple handlers with different content type. So for now it's OK not to do anything special about it, and leave it to the users customize the error handling as they wish.

Thanks for raising this concern! :+1:
